# Generated by Django 6.0.3 on 2026-05-14 15:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
        ('groups', '0004_rename_is_approved_groupmembership_is_verified'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan',
            name='amount_approved',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='amount_requested',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='duration_months',
        ),
        migrations.AlterField(
            model_name='loan',
            name='purpose',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='LoanRequestCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('duration_type', models.CharField(choices=[('MONTHS', 'months'), ('WEEKS', 'weeks'), ('DAYS', 'days')], default='MONTHS', max_length=20)),
                ('duration_count', models.PositiveIntegerField()),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans_request_category', to='groups.group')),
            ],
        ),
        migrations.AddField(
            model_name='loan',
            name='loan_request_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='finance.loanrequestcategories'),
            preserve_default=False,
        ),
    ]
