# Generated by Django 6.0.3 on 2026-06-02 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_loanproduct_snapshot_fields_and_finepayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanrepayment',
            name='payment_method',
            field=models.CharField(choices=[('MOBILE_MONEY', 'Mobile Money'), ('CREDIT_CARD', 'Credit Card'), ('CASH', 'Cash')], default='CASH', max_length=20),
        ),
        migrations.AlterField(
            model_name='loanproduct',
            name='interest_rate',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
