# Generated by Django 6.0.3 on 2026-06-03 04:46

import django.db.models.deletion
import uuid
from decimal import Decimal
from datetime import timedelta
from django.db import migrations, models
from django.utils import timezone


def _installment_step(duration_type):
    if duration_type == "DAYS":
        return timedelta(days=1)
    if duration_type == "WEEKS":
        return timedelta(weeks=1)
    return timedelta(days=30)


def backfill_loan_balances(apps, schema_editor):
    Loan = apps.get_model("finance", "Loan")
    LoanInstallment = apps.get_model("finance", "LoanInstallment")
    LoanRepayment = apps.get_model("finance", "LoanRepayment")

    today = timezone.now().date()

    for loan in Loan.objects.select_related("loan_product").all():
        repayments = list(LoanRepayment.objects.filter(loan=loan).order_by("paid_at", "created_at"))
        paid_total = Decimal("0.00")

        should_build_installments = bool(repayments) or loan.status in {
            "ACTIVE",
            "OVERDUE",
            "COMPLETED",
            "PAID_OFF",
            "DEFAULTED",
        }

        installments = []
        if should_build_installments:
            installment_count = max(1, loan.loan_product.duration_count)
            step = _installment_step(loan.loan_product.duration_type)
            start_date = (
                loan.disbursed_at.date()
                if loan.disbursed_at
                else loan.approved_at.date()
                if loan.approved_at
                else loan.created_at.date()
            )

            base_amount = (loan.total_repayment_amount / Decimal(installment_count)).quantize(
                Decimal("0.01")
            )
            running_total = Decimal("0.00")

            for installment_number in range(1, installment_count + 1):
                amount_due = (
                    loan.total_repayment_amount - running_total
                    if installment_number == installment_count
                    else base_amount
                )
                running_total += amount_due
                installments.append(
                    LoanInstallment.objects.create(
                        loan=loan,
                        installment_number=installment_number,
                        due_date=start_date + (step * installment_number),
                        amount_due=amount_due,
                        amount_paid=Decimal("0.00"),
                        status="PENDING",
                    )
                )

            installment_index = 0
            for repayment in repayments:
                remaining = repayment.amount
                while remaining > Decimal("0.00") and installment_index < len(installments):
                    installment = installments[installment_index]
                    installment_balance = installment.amount_due - installment.amount_paid
                    if installment_balance <= Decimal("0.00"):
                        installment_index += 1
                        continue

                    allocation = min(installment_balance, remaining)
                    repayment.installment_id = installment.id
                    repayment.save(update_fields=["installment"])

                    installment.amount_paid += allocation
                    paid_total += allocation
                    remaining -= allocation

                    if installment.amount_paid >= installment.amount_due:
                        installment.status = "PAID"
                    elif installment.amount_paid > Decimal("0.00"):
                        installment.status = "PARTIAL"
                    installment.save(update_fields=["amount_paid", "status"])

                    if installment.amount_paid >= installment.amount_due:
                        installment_index += 1

                if remaining > Decimal("0.00") and installments:
                    last_installment = installments[-1]
                    last_installment.amount_paid += remaining
                    paid_total += remaining
                    remaining = Decimal("0.00")
                    last_installment.status = "PAID"
                    last_installment.save(update_fields=["amount_paid", "status"])

            for installment in installments:
                if installment.amount_paid >= installment.amount_due:
                    installment.status = "PAID"
                elif installment.amount_paid > Decimal("0.00"):
                    installment.status = "PARTIAL"
                elif installment.due_date < today:
                    installment.status = "OVERDUE"
                else:
                    installment.status = "PENDING"
                installment.save(update_fields=["status"])
        else:
            paid_total = repayments and sum((repayment.amount for repayment in repayments), Decimal("0.00")) or Decimal("0.00")

        loan.amount_paid = paid_total.quantize(Decimal("0.01"))
        loan.remaining_balance = loan.total_repayment_amount - loan.amount_paid
        if loan.remaining_balance < Decimal("0.00"):
            loan.remaining_balance = Decimal("0.00")

        if loan.remaining_balance <= Decimal("0.00"):
            loan.status = "PAID_OFF"
        elif should_build_installments and any(
            installment.due_date < today and installment.amount_paid < installment.amount_due
            for installment in installments
        ):
            loan.status = "OVERDUE"

        loan.save(update_fields=["amount_paid", "remaining_balance", "status"])


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_loanrepayment_payment_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='loan',
            name='remaining_balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='loan',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('ACTIVE', 'Active'), ('PAID_OFF', 'Paid Off'), ('OVERDUE', 'Overdue'), ('COMPLETED', 'Completed'), ('DEFAULTED', 'Defaulted')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='loanrepayment',
            name='payment_method',
            field=models.CharField(choices=[('CASH', 'Cash'), ('MOBILE_MONEY', 'Mobile Money'), ('BANK', 'Bank'), ('CREDIT_CARD', 'Credit Card')], default='CASH', max_length=20),
        ),
        migrations.CreateModel(
            name='LoanInstallment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('installment_number', models.PositiveIntegerField()),
                ('due_date', models.DateField()),
                ('amount_due', models.DecimalField(decimal_places=2, max_digits=12)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PARTIAL', 'Partial'), ('PAID', 'Paid'), ('OVERDUE', 'Overdue')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installments', to='finance.loan')),
            ],
            options={
                'ordering': ['installment_number'],
            },
        ),
        migrations.AddField(
            model_name='loanrepayment',
            name='installment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='finance.loaninstallment'),
        ),
        migrations.RunPython(backfill_loan_balances, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='loaninstallment',
            constraint=models.UniqueConstraint(fields=('loan', 'installment_number'), name='unique_installment_number_per_loan'),
        ),
    ]
