# Generated by Django 6.0.3 on 2026-06-03 11:42

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_loan_amount_paid_loan_remaining_balance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanproduct',
            name='late_fee_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='loanproduct',
            name='use_group_default_late_fee',
            field=models.BooleanField(default=True),
        ),
    ]
