# Generated by Django 6.0.3 on 2026-06-03 12:25

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_loanproduct_late_fee_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loaninstallment',
            name='late_fee_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='loaninstallment',
            name='late_fee_paid',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
    ]
