# Generated by Django 6.0.3 on 2026-06-30 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0009_add_fine_category_and_enrich_fine'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='performed_by',
            field=models.CharField(blank=True, help_text='Name of the group member whose action this transaction records', max_length=255),
        ),
    ]
