# Generated by Django 6.0.3 on 2026-07-01 21:54

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


def backfill_wallets(apps, schema_editor):
    Group = apps.get_model("groups", "Group")
    GroupMembership = apps.get_model("groups", "GroupMembership")
    Contribution = apps.get_model("finance", "Contribution")
    Loan = apps.get_model("finance", "Loan")
    LoanRepayment = apps.get_model("finance", "LoanRepayment")
    Fine = apps.get_model("finance", "Fine")
    FinePayment = apps.get_model("finance", "FinePayment")
    GroupWallet = apps.get_model("finance", "GroupWallet")
    MemberWallet = apps.get_model("finance", "MemberWallet")

    for group in Group.objects.all():
        verified_savings = (
            Contribution.objects.filter(
                group=group,
                status=Contribution.Status.VERIFIED,
            ).aggregate(total=models.Sum("amount"))["total"]
            or Decimal("0.00")
        )

        loan_disbursed = (
            Loan.objects.filter(
                group=group,
                disbursed_at__isnull=False,
            ).aggregate(total=models.Sum("principal_amount"))["total"]
            or Decimal("0.00")
        )

        loan_repayments = (
            LoanRepayment.objects.filter(
                loan__group=group,
            ).aggregate(total=models.Sum("amount"))["total"]
            or Decimal("0.00")
        )

        fines_collected = (
            FinePayment.objects.filter(
                fine__group=group,
            ).aggregate(total=models.Sum("amount"))["total"]
            or Decimal("0.00")
        )

        group_wallet, _ = GroupWallet.objects.get_or_create(group=group)
        group_wallet.balance = verified_savings + loan_repayments + fines_collected - loan_disbursed
        group_wallet.total_verified_savings = verified_savings
        group_wallet.total_loan_disbursed = loan_disbursed
        group_wallet.total_loan_repayments = loan_repayments
        group_wallet.total_fines_collected = fines_collected
        group_wallet.save()

    for membership in GroupMembership.objects.select_related("group", "user").all():
        savings_balance = (
            Contribution.objects.filter(
                group=membership.group,
                member=membership,
                status=Contribution.Status.VERIFIED,
            ).aggregate(total=models.Sum("amount"))["total"]
            or Decimal("0.00")
        )

        loan_outstanding = (
            Loan.objects.filter(
                group=membership.group,
                borrower=membership,
            ).aggregate(total=models.Sum("remaining_balance"))["total"]
            or Decimal("0.00")
        )

        fine_outstanding = Decimal("0.00")
        for fine in Fine.objects.filter(
            group=membership.group,
            member=membership,
            status=Fine.Status.UNPAID,
        ).prefetch_related("payments"):
            paid = (
                fine.payments.aggregate(total=models.Sum("amount"))["total"]
                or Decimal("0.00")
            )
            fine_outstanding += fine.amount - paid

        wallet, _ = MemberWallet.objects.get_or_create(
            group=membership.group,
            member=membership,
        )
        wallet.savings_balance = savings_balance
        wallet.loan_outstanding = loan_outstanding
        wallet.fine_outstanding = fine_outstanding
        wallet.net_balance = savings_balance - loan_outstanding - fine_outstanding
        wallet.save()


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0010_transaction_performed_by'),
        ('groups', '0008_group_minimum_savings_for_loan'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total_verified_savings', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total_fines_collected', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total_loan_disbursed', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total_loan_repayments', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='finance_wallet', to='groups.group')),
            ],
            options={
                'ordering': ['group__name'],
            },
        ),
        migrations.CreateModel(
            name='MemberWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('savings_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('loan_outstanding', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('fine_outstanding', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('net_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_wallets', to='groups.group')),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='finance_wallet', to='groups.groupmembership')),
            ],
            options={
                'ordering': ['group__name', 'member__joined_at'],
                'constraints': [models.UniqueConstraint(fields=('group', 'member'), name='unique_member_wallet_per_group_member')],
            },
        ),
        migrations.RunPython(backfill_wallets, migrations.RunPython.noop),
    ]
