# Generated by Django 6.0.3 on 2026-05-14 13:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_groupinvitation_alter_groupmembership_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='groupmembership',
            options={'ordering': ['-joined_at']},
        ),
        migrations.RemoveConstraint(
            model_name='groupinvitation',
            name='unique_pending_invitation_per_group_email',
        ),
        migrations.RenameField(
            model_name='groupmembership',
            old_name='is_verified',
            new_name='is_approved',
        ),
        migrations.RemoveField(
            model_name='group',
            name='is_private',
        ),
        migrations.AddField(
            model_name='group',
            name='visibility',
            field=models.CharField(choices=[('PRIVATE', 'Private'), ('PUBLIC', 'Public')], default='PRIVATE', max_length=10),
        ),
        migrations.AddField(
            model_name='groupmembership',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='members',
            field=models.ManyToManyField(related_name='vikoba_groups', through='groups.GroupMembership', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='groupinvitation',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('DECLINED', 'Declined'), ('CANCELLED', 'Cancelled'), ('EXPIRED', 'Expired')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='groupmembership',
            name='role',
            field=models.CharField(choices=[('CHAIRPERSON', 'Chairperson'), ('SECRETARY', 'Secretary'), ('TREASURER', 'Treasurer'), ('MEMBER', 'Member')], default='MEMBER', max_length=20),
        ),
        migrations.AddIndex(
            model_name='group',
            index=models.Index(fields=['name'], name='groups_grou_name_0806de_idx'),
        ),
        migrations.AddIndex(
            model_name='group',
            index=models.Index(fields=['created_at'], name='groups_grou_created_b17bf8_idx'),
        ),
        migrations.AddIndex(
            model_name='groupmembership',
            index=models.Index(fields=['group'], name='groups_grou_group_i_c3781a_idx'),
        ),
        migrations.AddIndex(
            model_name='groupmembership',
            index=models.Index(fields=['user'], name='groups_grou_user_id_f265cb_idx'),
        ),
        migrations.AddConstraint(
            model_name='groupinvitation',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'PENDING')), fields=('group', 'email'), name='unique_pending_invitation_per_group_email'),
        ),
    ]
