# Generated by Django 6.0.3 on 2026-05-14 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_alter_group_options_alter_groupmembership_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groupmembership',
            old_name='is_approved',
            new_name='is_verified',
        ),
    ]
