# Generated by Django 6.0.3 on 2026-05-20 08:18

import apps.groups.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0004_rename_is_approved_groupmembership_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='join_code',
            field=models.CharField(default=apps.groups.models.generate_join_code, max_length=10, unique=True),
        ),
    ]
