# Generated by Django 6.0.3 on 2026-06-03 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0005_group_join_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='max_concurrent_loans',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
