# Generated by Django 6.0.3 on 2026-06-03 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0006_group_max_concurrent_loans'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='default_late_fee_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
