# Generated by Django 6.0.3 on 2026-07-02 00:00

from decimal import Decimal

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("groups", "0007_group_default_late_fee_amount"),
    ]

    operations = [
        migrations.AddField(
            model_name="group",
            name="minimum_savings_for_loan",
            field=models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=12),
        ),
    ]
