# Generated by Django 6.0.3 on 2026-06-14 07:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LedgerAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('account_type', models.CharField(choices=[('ASSET', 'Asset'), ('LIABILITY', 'Liability'), ('EQUITY', 'Equity'), ('REVENUE', 'Revenue'), ('EXPENSE', 'Expense')], max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('name', models.CharField(max_length=100)),
                ('provider_type', models.CharField(choices=[('CLICKPESA', 'Clickpesa'), ('MPESA', 'Mpesa'), ('AIRTEL', 'Airtel'), ('MIXX', 'Mixx'), ('BANK', 'Bank')], max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('configuration', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('reference', models.CharField(max_length=100, unique=True)),
                ('provider_reference', models.CharField(blank=True, max_length=255)),
                ('transaction_type', models.CharField(choices=[('COLLECTION', 'Collection'), ('PAYOUT', 'Payout'), ('TRANSFER', 'Transfer'), ('REFUND', 'Refund'), ('REVERSAL', 'Reversal')], max_length=30)),
                ('transaction_pursoses', models.CharField(choices=[('CONTRIBUTION', 'Contribution'), ('LOAN_REPAYMENT', 'Loan Repayment'), ('PENALTY_PAYMENT', 'Penalty Payment'), ('MEMBERSHIP_FEE', 'Membership Fee'), ('EVENT_PAYMENT', 'Event Payment')], max_length=30)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled'), ('REVERSED', 'Reversed')], default='DRAFT', max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('currency', models.CharField(default='TZS', max_length=10)),
                ('metadata', models.JSONField(default=dict)),
                ('initiated_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('wallet_type', models.CharField(choices=[('MEMBER', 'Member'), ('GROUP', 'Group'), ('SYSTEM', 'System'), ('ESCROW', 'Escrow')], max_length=20)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('available_balance', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('reserved_balance', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='LedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('debit', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('credit', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('narration', models.TextField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='payments.ledgeraccount')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='payments.paymenttransaction')),
            ],
        ),
        migrations.CreateModel(
            name='CollectionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('phone_number', models.CharField(max_length=20)),
                ('push_sent', models.BooleanField(default=False)),
                ('expires_at', models.DateTimeField()),
                ('payment_provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='payments.paymentprovider')),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='payments.paymenttransaction')),
            ],
        ),
        migrations.CreateModel(
            name='PayoutRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('beneficiary_name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=20)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='payments.paymentprovider')),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='payments.paymenttransaction')),
            ],
        ),
        migrations.CreateModel(
            name='Reversal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('reason', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('original_transaction', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='payments.paymenttransaction')),
                ('reversal_transaction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reversals', to='payments.paymenttransaction')),
                ('reversed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='destination_wallet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incoming_transactions', to='payments.wallet'),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='source_wallet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_transactions', to='payments.wallet'),
        ),
        migrations.CreateModel(
            name='WalletAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('account_type', models.CharField(choices=[('MOBILE_MONEY', 'Mobile Money'), ('BANK', 'Bank'), ('CARD', 'Card')], max_length=30)),
                ('account_number', models.CharField(max_length=100)),
                ('account_name', models.CharField(max_length=255)),
                ('is_default', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='payments.paymentprovider')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='payments.wallet')),
            ],
        ),
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('event_type', models.CharField(max_length=100)),
                ('payload', models.JSONField()),
                ('signature', models.TextField(blank=True)),
                ('processed', models.BooleanField(default=False)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='payments.paymentprovider')),
            ],
        ),
    ]
