# Generated by Django 6.0.3 on 2026-06-14 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymenttransaction',
            old_name='transaction_pursoses',
            new_name='purpose',
        ),
    ]
