# Generated by Django 6.0.3 on 2026-06-14 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_rename_transaction_pursoses_paymenttransaction_purpose'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ledgerentry',
            name='account',
        ),
        migrations.RemoveField(
            model_name='ledgerentry',
            name='transaction',
        ),
        migrations.DeleteModel(
            name='LedgerAccount',
        ),
        migrations.DeleteModel(
            name='LedgerEntry',
        ),
    ]
