# Generated by Django 6.0.3 on 2026-06-19 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_remove_ledgerentry_account_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='owner_uuid',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
    ]
