# Generated by Django 5.2 on 2026-07-27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0005_payment_payout_integrity"),
    ]

    operations = [
        migrations.AddField(
            model_name="webhookevent",
            name="headers",
            field=models.JSONField(default=dict, blank=True),
        ),
        migrations.AddField(
            model_name="webhookevent",
            name="ip_address",
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="webhookevent",
            name="processing_error",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="webhookevent",
            name="processing_result",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
