# Generated by Django 6.0.3 on 2026-04-29 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0004_minutesection'),
    ]

    operations = [
        migrations.AddField(
            model_name='minutesection',
            name='is_active_working',
            field=models.BooleanField(default=False, help_text='Currently being worked on by host'),
        ),
    ]
