# Generated by Django 6.0.3 on 2026-05-01 08:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0005_minutesection_is_active_working'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgendaMinuteNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('notes', models.TextField(blank=True, help_text='Public meeting minutes for this agenda item', null=True)),
                ('host_notes', models.TextField(blank=True, help_text='Private host notes for this agenda item', null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('ongoing', 'Ongoing'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('start_time', models.DateTimeField(blank=True, help_text='When this agenda item was started', null=True)),
                ('end_time', models.DateTimeField(blank=True, help_text='When this agenda item was completed', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agenda_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='minute_notes', to='meetings.agendaitem')),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agenda_minute_notes', to='meetings.meeting')),
            ],
            options={
                'ordering': ['agenda_item__order'],
                'unique_together': {('meeting', 'agenda_item')},
            },
        ),
    ]
