# Generated by Django 6.0.3 on 2026-05-04 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0007_additionalnote'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='agendaminutenote',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='agendaminutenote',
            name='title',
            field=models.CharField(blank=True, default='', help_text='Title for standalone notes (no agenda item)', max_length=255),
        ),
        migrations.AlterField(
            model_name='agendaminutenote',
            name='agenda_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='minute_notes', to='meetings.agendaitem'),
        ),
    ]
