# Generated by Django 6.0.3 on 2026-03-25 21:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('group_invitation', 'Group Invitation'), ('invitation_accepted', 'Invitation Accepted'), ('membership_verified', 'Membership Verified'), ('membership_activated', 'Membership Activated'), ('membership_deactivated', 'Membership Deactivated'), ('meeting_reminder', 'Meeting Reminder'), ('general', 'General')], default='general', max_length=50)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('group_uuid', models.UUIDField(blank=True, null=True)),
                ('invitation_uuid', models.UUIDField(blank=True, null=True)),
                ('membership_uuid', models.UUIDField(blank=True, null=True)),
                ('meeting_uuid', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
